import { Recipe, Unit } from '../types';

export const DEFAULT_RECIPES: Recipe[] = [
  {
    id: 'sayur-asem',
    name: 'Sayur Asem Segar',
    category: 'Sayuran',
    description: 'Sayur asem khas Sunda/Betawi dengan kuah asam manis gurih dan sayuran renyah.',
    defaultServings: 4,
    cookTimeMinutes: 30,
    difficulty: 'Mudah',
    instructions: [
      'Rebus air hingga mendidih bersama jagung manis, melinjo, dan kacang tanah hingga empuk.',
      'Haluskan bumbu (bawang merah, bawang putih, cabai merah, kemiri, terasi bakar, dan garam).',
      'Masukkan bumbu halus, lengkuas, daun salam, dan air asam jawa ke dalam panci.',
      'Masukkan labu siam dan kacang panjang, masak hingga sayuran matang.',
      'Tambahkan daun melinjo, gula pasir, dan kaldu bubuk. Koreksi rasa asam, manis, dan gurih lalu angkat.'
    ],
    ingredients: [
      { name: 'Jagung Manis', quantity: 2, unit: Unit.BUAH, category: 'Sayuran', estimatedPrice: 8000, note: 'Potong-potong bulat' },
      { name: 'Labu Siam', quantity: 1, unit: Unit.BUAH, category: 'Sayuran', estimatedPrice: 4000, note: 'Kupas & potong dadu' },
      { name: 'Kacang Panjang', quantity: 1, unit: Unit.IKAT, category: 'Sayuran', estimatedPrice: 3000, note: 'Potong 3 cm' },
      { name: 'Melinjo & Daun Melinjo', quantity: 1, unit: Unit.BUNGKUS, category: 'Sayuran', estimatedPrice: 4000 },
      { name: 'Kacang Tanah', quantity: 100, unit: Unit.GRAM, category: 'Sembako', estimatedPrice: 4000 },
      { name: 'Asam Jawa', quantity: 1, unit: Unit.BUNGKUS, category: 'Bumbu Dapur', estimatedPrice: 2500 },
      { name: 'Bawang Merah', quantity: 6, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 3000 },
      { name: 'Bawang Putih', quantity: 3, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 2000 },
      { name: 'Cabai Merah Keriting', quantity: 3, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 2000 },
      { name: 'Lengkuas', quantity: 1, unit: Unit.BUNGKUS, category: 'Bumbu Dapur', estimatedPrice: 2000, note: 'Memarkan' },
      { name: 'Terasi', quantity: 1, unit: Unit.BUNGKUS, category: 'Bumbu Dapur', estimatedPrice: 1500, note: 'Bakar sedikit' },
    ]
  },
  {
    id: 'soto-ayam',
    name: 'Soto Ayam Lamongan',
    category: 'Sup & Berkuah',
    description: 'Soto ayam berkuah kuning wangi rempah dengan suwiran ayam, bihun, tauge, dan bubuk koya gurih.',
    defaultServings: 4,
    cookTimeMinutes: 45,
    difficulty: 'Sedang',
    instructions: [
      'Rebus ayam dalam 1,5 liter air hingga kaldu harum dan ayam matang empuk.',
      'Haluskan bawang merah, bawang putih, kunyit bakar, jahe, kemiri, ketumbar, dan merica.',
      'Tumis bumbu halus bersama serai, daun salam, dan daun jeruk sampai matang dan harum.',
      'Tuang tumisan bumbu ke dalam kuah rebusan ayam, bumbui dengan garam dan kaldu bubuk.',
      'Angkat ayam, tiriskan, goreng sebentar lalu suwir-suwir dagingnya.',
      'Sajikan dalam mangkuk: bihun, kol iris, tauge, suwiran ayam, siram kuah panas, beri seledri, koya, dan perasan jeruk nipis.'
    ],
    ingredients: [
      { name: 'Daging Ayam', quantity: 0.5, unit: Unit.KG, category: 'Daging & Ikan', estimatedPrice: 20000, note: 'Dada atau paha' },
      { name: 'Bihun', quantity: 1, unit: Unit.BUNGKUS, category: 'Sembako', estimatedPrice: 5000, note: 'Seduh air panas' },
      { name: 'Toge / Tauge', quantity: 1, unit: Unit.BUNGKUS, category: 'Sayuran', estimatedPrice: 3000 },
      { name: 'Kol', quantity: 0.25, unit: Unit.BUAH, category: 'Sayuran', estimatedPrice: 3000, note: 'Iris halus' },
      { name: 'Bawang Merah', quantity: 8, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 4000 },
      { name: 'Bawang Putih', quantity: 5, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 3000 },
      { name: 'Kunyit', quantity: 1, unit: Unit.BUNGKUS, category: 'Bumbu Dapur', estimatedPrice: 2000 },
      { name: 'Jahe', quantity: 1, unit: Unit.BUNGKUS, category: 'Bumbu Dapur', estimatedPrice: 2000 },
      { name: 'Serai & Daun Jeruk', quantity: 1, unit: Unit.IKAT, category: 'Bumbu Dapur', estimatedPrice: 2500 },
      { name: 'Jeruk Nipis', quantity: 2, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 3000 },
      { name: 'Seledri & Daun Bawang', quantity: 1, unit: Unit.IKAT, category: 'Sayuran', estimatedPrice: 3000 },
      { name: 'Telur Ayam', quantity: 2, unit: Unit.BIJI, category: 'Sembako', estimatedPrice: 4500, note: 'Rebus matang' },
    ]
  },
  {
    id: 'rendang-sapi',
    name: 'Rendang Daging Sapi',
    category: 'Daging & Ayam',
    description: 'Rendang daging sapi Minang autentik dengan bumbu rempah pekat dan santan kental yang meresap.',
    defaultServings: 6,
    cookTimeMinutes: 120,
    difficulty: 'Spesial',
    instructions: [
      'Potong-potong daging sapi sesuai selera mengikuti arah serat daging.',
      'Haluskan cabai merah keriting, bawang merah, bawang putih, jahe, lengkuas, kunyit, dan ketumbar.',
      'Rebus santan kental bersama bumbu halus, serai, daun kunyit, asam kandis, dan daun jeruk sambil terus diaduk agar santan tidak pecah.',
      'Setelah santan mengeluarkan minyak dan harum, masukkan potongan daging sapi.',
      'Kecilkan api, masak perlahan sambil sesekali diaduk hingga kuah menyusut, berwarna cokelat gelap, dan daging empuk meresap.'
    ],
    ingredients: [
      { name: 'Daging Sapi', quantity: 0.5, unit: Unit.KG, category: 'Daging & Ikan', estimatedPrice: 65000, note: 'Potong ukuran rendang' },
      { name: 'Santan Kelapa', quantity: 2, unit: Unit.BUNGKUS, category: 'Sembako', estimatedPrice: 12000, note: 'Santan kental murni' },
      { name: 'Cabai Merah Keriting', quantity: 150, unit: Unit.GRAM, category: 'Bumbu Dapur', estimatedPrice: 8000 },
      { name: 'Bawang Merah', quantity: 10, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 5000 },
      { name: 'Bawang Putih', quantity: 6, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 3500 },
      { name: 'Lengkuas', quantity: 1, unit: Unit.BUNGKUS, category: 'Bumbu Dapur', estimatedPrice: 2000 },
      { name: 'Jahe', quantity: 1, unit: Unit.BUNGKUS, category: 'Bumbu Dapur', estimatedPrice: 2000 },
      { name: 'Serai', quantity: 2, unit: Unit.BATANG || Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 2000 },
      { name: 'Ketumbar Bubuk', quantity: 1, unit: Unit.SACHET, category: 'Bumbu Dapur', estimatedPrice: 1500 },
      { name: 'Daun Jeruk & Daun Kunyit', quantity: 1, unit: Unit.BUNGKUS, category: 'Bumbu Dapur', estimatedPrice: 2500 },
    ]
  },
  {
    id: 'sayur-lodeh',
    name: 'Sayur Lodeh Tahu Tempe',
    category: 'Sayuran',
    description: 'Sayuran kuah santan gurih sedap dipadukan potongan tahu, tempe, labu siam, dan cabai hijau.',
    defaultServings: 4,
    cookTimeMinutes: 30,
    difficulty: 'Mudah',
    instructions: [
      'Potong dadu tempe, tahu putih, dan labu siam. Potong kacang panjang.',
      'Tumis irisan bawang merah, bawang putih, cabai hijau keriting, daun salam, dan lengkuas sampai wangi.',
      'Tuangkan air dan santan, aduk perlahan agar santan rata.',
      'Masukkan labu siam, tempe, tahu, dan kacang panjang.',
      'Bumbui dengan garam, gula merah, dan sedikit kaldu bubuk. Masak dengan api sedang hingga matang merata.'
    ],
    ingredients: [
      { name: 'Tahu', quantity: 1, unit: Unit.BUNGKUS, category: 'Sembako', estimatedPrice: 5000, note: 'Potong dadu' },
      { name: 'Tempe', quantity: 1, unit: Unit.BUNGKUS, category: 'Sembako', estimatedPrice: 4000, note: 'Potong dadu' },
      { name: 'Waluh / Labu Siam', quantity: 1, unit: Unit.BUAH, category: 'Sayuran', estimatedPrice: 4000 },
      { name: 'Kacang Panjang', quantity: 1, unit: Unit.IKAT, category: 'Sayuran', estimatedPrice: 3000 },
      { name: 'Santan Kelapa', quantity: 1, unit: Unit.BUNGKUS, category: 'Sembako', estimatedPrice: 4000 },
      { name: 'Cabai Hijau Keriting', quantity: 50, unit: Unit.GRAM, category: 'Bumbu Dapur', estimatedPrice: 3000, note: 'Iris serong' },
      { name: 'Bawang Merah', quantity: 6, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 3000 },
      { name: 'Bawang Putih', quantity: 4, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 2000 },
      { name: 'Gula Merah', quantity: 1, unit: Unit.BUNGKUS, category: 'Sembako', estimatedPrice: 3000 },
    ]
  },
  {
    id: 'capcay-goreng',
    name: 'Capcay Goreng Bakso & Ayam',
    category: 'Lauk Pauk',
    description: 'Tumis aneka sayuran segar renyah dengan potongan bakso, daging ayam, dan saus tiram gurih.',
    defaultServings: 4,
    cookTimeMinutes: 20,
    difficulty: 'Mudah',
    instructions: [
      'Siapkan dan potong-potong wortel, kembang kol, brokoli, sawi hijau, dan kol.',
      'Panaskan minyak, tumis bawang putih cincang dan bawang bombay sampai harum dan sedikit layu.',
      'Masukkan fillet ayam dan irisan bakso, masak sampai berubah warna.',
      'Masukkan wortel dan kembang kol terlebih dahulu karena teksturnya lebih keras, beri sedikit air.',
      'Masukkan sawi hijau, saus tiram, kecap asin, merica, dan garam.',
      'Kentalkan dengan larutan tepung maizena/tapioka, aduk cepat lalu angkat saat sayur masih renyah.'
    ],
    ingredients: [
      { name: 'Wortel', quantity: 2, unit: Unit.BUAH, category: 'Sayuran', estimatedPrice: 4000, note: 'Iris serong' },
      { name: 'Kembang Kol / Brokoli', quantity: 1, unit: Unit.BUNGKUS, category: 'Sayuran', estimatedPrice: 7000 },
      { name: 'Sawi', quantity: 1, unit: Unit.IKAT, category: 'Sayuran', estimatedPrice: 3000 },
      { name: 'Bakso Sapi', quantity: 1, unit: Unit.BUNGKUS, category: 'Sembako', estimatedPrice: 12000, note: 'Iris bulat' },
      { name: 'Daging Ayam', quantity: 150, unit: Unit.GRAM, category: 'Daging & Ikan', estimatedPrice: 7000, note: 'Fillet potong kecil' },
      { name: 'Bawang Bombay', quantity: 1, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 4000 },
      { name: 'Bawang Putih', quantity: 4, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 2500, note: 'Cincang halus' },
      { name: 'Saus Tiram', quantity: 1, unit: Unit.BOTOL, category: 'Bumbu Dapur', estimatedPrice: 6000 },
      { name: 'Minyak Goreng', quantity: 50, unit: Unit.ML, category: 'Sembako', estimatedPrice: 1500 },
    ]
  },
  {
    id: 'opor-ayam',
    name: 'Opor Ayam Gurih',
    category: 'Daging & Ayam',
    description: 'Ayam berkuah santan kental bumbu rempah kuning wangi, teman setia ketupat atau nasi hangat.',
    defaultServings: 5,
    cookTimeMinutes: 40,
    difficulty: 'Sedang',
    instructions: [
      'Lumuri potongan ayam dengan perasan air jeruk nipis dan sedikit garam, diamkan 10 menit lalu bilas.',
      'Haluskan bawang merah, bawang putih, kunyit, kemiri sangrai, ketumbar, jahe, dan merica.',
      'Tumis bumbu halus bersama serai, daun salam, daun jeruk, dan lengkuas sampai tanak harum.',
      'Masukkan ayam, aduk sampai ayam kaku dan berubah warna.',
      'Tuangkan santan cair dan santan kental. Masak dengan api kecil-sedang sambil sesekali diaduk perlahan.',
      'Tambahkan garam, gula pasir, dan kaldu bubuk. Masak sampai kuah meresap dan ayam empuk lembut.'
    ],
    ingredients: [
      { name: 'Daging Ayam', quantity: 0.8, unit: Unit.KG, category: 'Daging & Ikan', estimatedPrice: 32000, note: 'Potong 8-10 bagian' },
      { name: 'Santan Kelapa', quantity: 2, unit: Unit.BUNGKUS, category: 'Sembako', estimatedPrice: 8000 },
      { name: 'Bawang Merah', quantity: 8, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 4000 },
      { name: 'Bawang Putih', quantity: 5, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 3000 },
      { name: 'Kemiri', quantity: 1, unit: Unit.BUNGKUS, category: 'Bumbu Dapur', estimatedPrice: 2000, note: 'Sangrai' },
      { name: 'Kunyit', quantity: 1, unit: Unit.BUNGKUS, category: 'Bumbu Dapur', estimatedPrice: 2000 },
      { name: 'Ketumbar Bubuk', quantity: 1, unit: Unit.SACHET, category: 'Bumbu Dapur', estimatedPrice: 1500 },
      { name: 'Serai & Lengkuas', quantity: 1, unit: Unit.IKAT, category: 'Bumbu Dapur', estimatedPrice: 2500 },
      { name: 'Bawang Goreng', quantity: 1, unit: Unit.BUNGKUS, category: 'Bumbu Dapur', estimatedPrice: 3500, note: 'Untuk taburan' },
    ]
  },
  {
    id: 'sambal-goreng-ati',
    name: 'Sambal Goreng Kentang Ati Ampela',
    category: 'Lauk Pauk',
    description: 'Kentang potong dadu goreng renyah dipadu potongan hati ampela dan kuah santan cabai merah sedap.',
    defaultServings: 4,
    cookTimeMinutes: 35,
    difficulty: 'Sedang',
    instructions: [
      'Potong dadu kentang, goreng sampai berkulit keemasan lalu tiriskan.',
      'Rebus hati ampela dengan jahe dan daun salam sampai matang, lalu potong dadu.',
      'Haluskan cabai merah besar, cabai rawit, bawang merah, bawang putih, dan tomat.',
      'Tumis bumbu halus bersama lengkuas dan serai sampai matang dan berminyak.',
      'Masukkan potongan hati ampela, santan, garam, dan gula merah. Masak hingga kuah mengental.',
      'Masukkan kentang goreng dan cabai merah iris, aduk rata sebentar sampai bumbu merata lalu angkat.'
    ],
    ingredients: [
      { name: 'Kentang', quantity: 0.5, unit: Unit.KG, category: 'Sayuran', estimatedPrice: 9000, note: 'Potong dadu kecil' },
      { name: 'Hati Ampela Ayam', quantity: 4, unit: Unit.SET || Unit.BUAH, category: 'Daging & Ikan', estimatedPrice: 12000 },
      { name: 'Cabai Merah', quantity: 100, unit: Unit.GRAM, category: 'Bumbu Dapur', estimatedPrice: 6000 },
      { name: 'Cabai Rawit (Cengek)', quantity: 50, unit: Unit.GRAM, category: 'Bumbu Dapur', estimatedPrice: 3500 },
      { name: 'Bawang Merah', quantity: 7, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 3500 },
      { name: 'Bawang Putih', quantity: 4, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 2500 },
      { name: 'Santan Kelapa', quantity: 1, unit: Unit.BUNGKUS, category: 'Sembako', estimatedPrice: 4000 },
      { name: 'Minyak Goreng', quantity: 250, unit: Unit.ML, category: 'Sembako', estimatedPrice: 4500, note: 'Untuk menggoreng' },
    ]
  },
  {
    id: 'bakwan-sayur',
    name: 'Bakwan Sayur Renyah & Gurih',
    category: 'Gorengan & Lauk',
    description: 'Camilan dan pelengkap makan favorit: gorengan sayur kol, wortel, dan tauge dengan tepung berbumbu renyah.',
    defaultServings: 4,
    cookTimeMinutes: 20,
    difficulty: 'Mudah',
    instructions: [
      'Iris halus kol, serut wortel tipis memanjang, dan cuci bersih tauge.',
      'Haluskan bawang putih, ketumbar, merica, dan garam.',
      'Campur tepung terigu, tepung beras (sedikit agar renyah), bumbu halus, dan daun bawang iris.',
      'Tuangkan air es sedikit demi sedikit hingga kekentalan adonan pas.',
      'Masukkan sayuran ke dalam adonan, aduk rata.',
      'Goreng sendokan adonan dalam minyak banyak dan panas sampai kuning keemasan dan renyah. Sajikan dengan cabai rawit.'
    ],
    ingredients: [
      { name: 'Tepung Terigu', quantity: 250, unit: Unit.GRAM, category: 'Sembako', estimatedPrice: 3500 },
      { name: 'Kol', quantity: 0.25, unit: Unit.BUAH, category: 'Sayuran', estimatedPrice: 2500, note: 'Iris halus' },
      { name: 'Wortel', quantity: 2, unit: Unit.BUAH, category: 'Sayuran', estimatedPrice: 3500, note: 'Iris korek api' },
      { name: 'Toge / Tauge', quantity: 1, unit: Unit.BUNGKUS, category: 'Sayuran', estimatedPrice: 2500 },
      { name: 'Bawang Daun', quantity: 1, unit: Unit.IKAT, category: 'Bumbu Dapur', estimatedPrice: 2500 },
      { name: 'Bawang Putih', quantity: 3, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 1500 },
      { name: 'Ketumbar Bubuk', quantity: 1, unit: Unit.SACHET, category: 'Bumbu Dapur', estimatedPrice: 1500 },
      { name: 'Minyak Goreng', quantity: 0.5, unit: Unit.LITER, category: 'Sembako', estimatedPrice: 9000 },
      { name: 'Cabai Rawit (Cengek)', quantity: 50, unit: Unit.GRAM, category: 'Bumbu Dapur', estimatedPrice: 3000, note: 'Teman makan bakwan' },
    ]
  },
  {
    id: 'nasi-goreng-spesial',
    name: 'Nasi Goreng Spesial Rumahan',
    category: 'Nasi & Mie',
    description: 'Nasi goreng harum sedap bumbu bawang, telur orak-arik, bakso, dan kecap manis khas Indonesia.',
    defaultServings: 3,
    cookTimeMinutes: 15,
    difficulty: 'Mudah',
    instructions: [
      'Siapkan nasi pera dingin (sebaiknya nasi kemarin atau dari kulkas).',
      'Tumis cincangan bawang merah, bawang putih, dan irisan cabai rawit sampai harum.',
      'Sisihkan bumbu ke pinggir wajan, masukkan telur lalu orak-arik sampai matang.',
      'Masukkan irisan bakso dan daging ayam/sosis, aduk bersama telur dan bumbu.',
      'Masukkan nasi putih, beri kecap manis, kecap asin/saus tiram, garam, dan merica bubuk.',
      'Aduk cepat dengan api besar hingga nasi berasap dan bumbu meresap sempurna. Sajikan hangat.'
    ],
    ingredients: [
      { name: 'Beras', quantity: 0.5, unit: Unit.KG, category: 'Sembako', estimatedPrice: 7500, note: 'Nasi siap saji' },
      { name: 'Telur Ayam', quantity: 3, unit: Unit.BIJI, category: 'Sembako', estimatedPrice: 6500 },
      { name: 'Bakso Sapi', quantity: 5, unit: Unit.BUAH, category: 'Sembako', estimatedPrice: 6000, note: 'Iris tipis' },
      { name: 'Bawang Merah', quantity: 5, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 2500 },
      { name: 'Bawang Putih', quantity: 3, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 1500 },
      { name: 'Cabai Rawit (Cengek)', quantity: 5, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 2000 },
      { name: 'Kecap Manis', quantity: 1, unit: Unit.BUNGKUS, category: 'Sembako', estimatedPrice: 3500 },
      { name: 'Bawang Daun', quantity: 1, unit: Unit.IKAT, category: 'Bumbu Dapur', estimatedPrice: 2500 },
      { name: 'Timun', quantity: 1, unit: Unit.BUAH, category: 'Sayuran', estimatedPrice: 2000, note: 'Lalapan acar' },
    ]
  },
  {
    id: 'tumis-kangkung-terasi',
    name: 'Tumis Kangkung Belacan / Terasi',
    category: 'Sayuran',
    description: 'Kangkung hijau segar ditumis cepat dengan bumbu terasi harum, gurih, dan pedas nikmat.',
    defaultServings: 3,
    cookTimeMinutes: 10,
    difficulty: 'Mudah',
    instructions: [
      'Petik daun kangkung dan batangnya yang muda, cuci bersih lalu tiriskan.',
      'Tumis irisan bawang merah, bawang putih, cabai merah, cabai rawit, dan terasi bakar sampai harum semerbak.',
      'Masukkan tomat iris dan saus tiram.',
      'Masukkan kangkung, besarkan api wajan, tumis cepat agar warnanya tetap hijau segar dan renyah.',
      'Bumbui dengan sedikit garam dan gula. Masak sebentar saja (1-2 menit) lalu segera matikan api.'
    ],
    ingredients: [
      { name: 'Kangkung', quantity: 2, unit: Unit.IKAT, category: 'Sayuran', estimatedPrice: 5000 },
      { name: 'Bawang Merah', quantity: 5, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 2500 },
      { name: 'Bawang Putih', quantity: 3, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 1500 },
      { name: 'Cabai Rawit (Cengek)', quantity: 5, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 2000 },
      { name: 'Cabai Merah Keriting', quantity: 3, unit: Unit.BUAH, category: 'Bumbu Dapur', estimatedPrice: 2000 },
      { name: 'Terasi', quantity: 1, unit: Unit.BUNGKUS, category: 'Bumbu Dapur', estimatedPrice: 1500, note: 'Bakar sedikit' },
      { name: 'Tomat', quantity: 1, unit: Unit.BUAH, category: 'Sayuran', estimatedPrice: 1500 },
      { name: 'Saus Tiram', quantity: 1, unit: Unit.SACHET, category: 'Bumbu Dapur', estimatedPrice: 2500 },
    ]
  }
];
